name: Run_Test_Hyper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    env:
      CYPRESS_API_URL: https://sorry-cypress-gateway-verso-services.gp-nonprod-na-0.conde.digital/director
      COMMIT_INFO_MESSAGE: "Ritam"
      CYPRESS_BEARER_TOKEN: "abc"
      CYPRESS_BEARER_TOKEN_STAG: "xy"
      CYPRESS_PURGE_TOKEN: "ab"
      CYPRESS_SECRET_KEY_PROD: ${{ secrets.CYPRESS_SECRET_KEY_PROD }}
      CYPRESS_SECRET_KEY_STAG: ${{ secrets.CYPRESS_SECRET_KEY_STAG }}
      CYPRESS_IS_CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust to your desired Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Run Cypress Tests
        run: |
          curl -O https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
          chmod u+x hyperexecute
          ./hyperexecute --user vishnukdas --key E2dKmfNG5TkW2DbKwpUrvtD0XAo9PUmuB6Q35A60T6whHotlnR --config hyperExe.yml
          
